version: '3.9'
services:
  postgres-pedidos:
    image: postgres:14
    container_name: postgres-pedidos
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mcP4ss
      POSTGRES_DB: pedidos
    ports:
      - "5432:5432"
    volumes:
      - postgres-pedidos-data:/var/lib/postgresql/data

  postgres-usuarios:
    image: postgres:14
    container_name: postgres-usuarios
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mcP4ss
      POSTGRES_DB: usuarios
    ports:
      - "5433:5432"
    volumes:
      - postgres-usuarios-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mcP4ss
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  postgres-pedidos-data:
    driver: local
  postgres-usuarios-data:
    driver: local
  mongo-data:
    driver: local
